### ISSUE TITLE
Add breakpoints

### ISSUE THREAD

**Issue by wawachief** [wawachief/DigiQt#26]
Clicking on a line number should add/remove a breakpoint.
A breakpoint is displayed by highlighting the line number (in red).

IHM should generate a list containing the lines where breakpoints should be placed.
Controller will take that list and pass it to the assembler.
The assembler will convert it to a list of program counter adresses which will make the CPU stop.

**Comment by ThomasLecluse** [comment]
HMI done.
You may use CodeEditor.get_breakpoints() method to retrieve all the breakpoints added by the user.

**Comment by wawachief** [comment]
done
